language: perl
perl:
  - "5.18"
  - "5.20"
  - "5.22"
  - "5.24"
  - "5.26"
before_install:
  - cpanm --notest --quiet Dist::Zilla Dist::Zilla::App::Command::cover Devel::Cover::Report::Codecov Devel::Cover::Report::Coveralls
  - dzil authordeps | cpanm --notest --quiet
  - cpanm --notest --quiet Pod::Coverage::TrustPod

install:
  - dzil listdeps | cpanm --notest --quiet

script:
  - dzil test --release --verbose
  - dzil cover -test

after_success:
  - cover -report coveralls
  - cover -report codecov
